/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "mux_4x1_gatelevel.v:3.1-25.10" *)
module mux_4x1_gatelevel(in, sel, out);
  (* src = "mux_4x1_gatelevel.v:4.15-4.17" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "mux_4x1_gatelevel.v:5.15-5.18" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "mux_4x1_gatelevel.v:6.10-6.13" *)
  output out;
  wire out;
  wire _0_;
  wire _1_;
  assign _0_ = sel[0] ? in[3] : in[2];
  assign _1_ = sel[0] ? in[1] : in[0];
  assign out = sel[1] ? _0_ : _1_;
endmodule
